# Generated by Django 3.0.6 on 2020-06-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    initial = True

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Email_verification',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1024)),
                ('expiry', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(1, 'Student'), (2, 'Admin'), (3, 'Internal team'), (4, 'Teacher'), (5, 'Others')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ORMUser',
            fields=[
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('userimage', models.ImageField(upload_to=None)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30, null=True)),
                ('disable_account', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField()),
                ('login_count', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.Department')),
                ('initiatives', models.ManyToManyField(to='initiatives.ORMInitiative')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.Role')),
                ('skill', models.ManyToManyField(to='useraccounts.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='ORMProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.IntegerField()),
                ('proj_name', models.CharField(max_length=50)),
                ('proj_description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.ORMUser')),
            ],
        ),
    ]
