# Generated by Django 3.0.6 on 2020-06-08 14:11

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('useraccounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ormproject',
            old_name='proj_description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='ormproject',
            old_name='proj_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='ormproject',
            old_name='proj_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='id',
            new_name='role_id',
        ),
    ]
