# Generated by Django 3.0.6 on 2020-06-08 14:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    

    dependencies = [
        ('useraccounts', '0003_auto_20200608_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='ormproject',
            name='user_id',
        ),
    ]
