# Generated by Django 3.0.6 on 2020-06-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_auto_20200608_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ormuser',
            name='initiatives',
        ),
        migrations.AlterField(
            model_name='ormuser',
            name='role',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Admin'), ('3', 'Internal team'), ('4', 'Teacher'), ('5', 'Others')], default='1', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
